bot:
  token: ''
  ownerid: 506057411749216257
  guildid: 924026721571856434
  birthdaychannel: 924026721571856437
database:
  ip: 'localhost'
  port: 3306
  database: 'birthdays'
  user: 'root'
  password: ''
gifs:
  - 'https://media1.tenor.com/m/alwkw27l-tsAAAAC/happy-birthday-donut.gif'
  - 'https://media1.tenor.com/m/7ta-bOJwdwgAAAAC/happy-birthday-cat.gif'