bot:
  token: 'MTIyNjk3NDA4ODM2NzU3NTEyMA.GwEZlP.O8qJrjxrmNWFz3xrpnfDuZa_mpeAUn-0-1_5sA'
  ownerid: 506057411749216257
  guildid: 924026721571856434
  birthdaychannel: 924026721571856437
database:
  ip: 'localhost'
  port: 3306
  database: 'birthdays'
  user: 'root'
  password: ''